//
//  Define.h
//  Choukyu
//
//  Created by shamaton.
//
//

#ifndef Choukyu_Define_h
#define Choukyu_Define_h

#define MIN_LEVEL 1 // 敵の最小レベル
#define MAX_LEVEL 5 // 敵の最大レベル

#define MAX_TOTAL_DAMAGE 99999999 // 蓄積ダメージの最大
#define MAX_COMBO        999      // 最大コンボ
#define MAX_ATTACK_VALUE 9999     // 最大攻撃力
#define MAX_RATE         100      // 最高率

#define DAMAGE_TEXT_NUM 7

// TAGS
enum E_TAG {
	TAG_NULL = 0,
	TAG_PLAYER,
	TAG_ENEMY,
	TAG_ATTACK_EFFECT_TATE,
	TAG_ATTACK_EFFECT_YOKO,
	TAG_ATTACK_EFFECT_NANAME,
	TAG_DAMAGE_EFFECT,
	TAG_CHARGE,
	TAG_INPUT_GAUGE,
	TAG_DAMEGE_TEXT = 100, // - 200 まで連番使用
	TAG_MESSAGE_WINDOW = 200,
	TAG_CHAIN = 299,
	TAG_HINTS = 300,
	TAG_LIMIT_BREAK = 400,
	TAG_LIMIT_BREAK_NUM,
	TAG_TOUCH_BUTTON_NODE = 990,
	TAG_TOUCH_BUTTON = 1000,
	TAG_TOUCH_NUMBER = 1100,
	TAG_TOUCH_EFFECT = 1200,
	TAG_LINE_NUM = 2000,
	TAG_FIXED_LINE,
    TAG_MOTION_STREAK,
	TAG_COUNTDOWN,
	TAG_JUDGE_EFFECT,
    TAG_MESSAGE_WINDOW_LAYER, // new
	NR_TAG
};

enum E_Z_ORDER {
	Z_NULL = 0,
	ORDER_BACKGROUND,
	ORDER_CHARACTER,
	ORDER_EFFECT,
	ORDER_DAMAGE_TEXT,
	ORDER_GAUGE,
	ORDER_GAUGE_WAKU,
	ORDER_TOUCH_LINE,
	ORDER_TOUCH_PANEL,
	ORDER_TOUCH_NUMBER,
	ORDER_COUNTDOWN,
	ORDER_HINTS,
	ORDER_UI,
    ORDER_MESSAGE_WINDOW_LAYER, // new
	NR_Z_ORDER
};

enum DIRECTION {
	UP,
	DOWN,
	LEFT,
	RIGHT,
	UP_LEFT,
	UP_RIGHT,
	DOWN_LEFT,
	DOWN_RIGHT,
};

#endif
